#!/usr/bin/env node
/*
 * Compiles content/posts/ into js/posts.js and validates all HTML/JS.
 * Run: node build.js
 */
const fs = require('fs');
const vm = require('vm');
const path = require('path');

let errors = 0;
function fail(msg) { console.error('  ERROR:', msg); errors++; }

// ── 1. Build posts.js from individual JSONs ──
console.log('Building js/posts.js...');
const index = JSON.parse(fs.readFileSync('content/posts/index.json', 'utf8'));
const posts = index.map(slug => {
  const file = `content/posts/${slug}.json`;
  if (!fs.existsSync(file)) { fail(`${file} not found`); return null; }
  const p = JSON.parse(fs.readFileSync(file, 'utf8'));
  // Validate required fields
  for (const f of ['slug', 'title', 'date', 'image', 'tags', 'body']) {
    if (!p[f]) fail(`${slug}.json missing "${f}"`);
  }
  if (p.slug !== slug) fail(`${slug}.json: slug "${p.slug}" doesn't match filename`);
  // Validate image files exist
  const imgs = [p.image, ...(p.images || [])];
  imgs.forEach(img => {
    if (img && !fs.existsSync(img)) fail(`${slug}: image not found: ${img}`);
  });
  return p;
}).filter(Boolean);

const out = `/* Auto-generated by build.js — do not edit directly. */\nconst posts = ${JSON.stringify(posts, null, 2)};\n`;
fs.writeFileSync('js/posts.js', out);
console.log(`  ${index.length} posts compiled`);

// ── 2. Validate JS in HTML files ──
console.log('Validating scripts...');
const htmlFiles = ['gallery.html', 'post.html', 'index.html'];
htmlFiles.forEach(file => {
  if (!fs.existsSync(file)) return;
  const html = fs.readFileSync(file, 'utf8');

  // Extract inline <script> blocks (skip ones with src)
  const scriptRe = /<script(?![^>]*\bsrc\b)[^>]*>([\s\S]*?)<\/script>/gi;
  let match, blockIdx = 0;
  while ((match = scriptRe.exec(html)) !== null) {
    blockIdx++;
    const code = match[1].trim();
    if (!code) continue;
    try {
      new vm.Script(code, { filename: `${file} <script #${blockIdx}>` });
    } catch (e) {
      fail(`${file} <script #${blockIdx}>: ${e.message}`);
    }
  }

  // Check external script files exist
  const srcRe = /<script[^>]+src="([^"]+)"/gi;
  while ((match = srcRe.exec(html)) !== null) {
    if (match[1].startsWith('http')) continue;
    if (!fs.existsSync(match[1])) fail(`${file}: script not found: ${match[1]}`);
  }
});

// ── 3. Validate generated posts.js itself ──
try {
  new vm.Script(fs.readFileSync('js/posts.js', 'utf8'), { filename: 'js/posts.js' });
} catch (e) {
  fail(`js/posts.js: ${e.message}`);
}

// ── 4. Check tagCN coverage ──
const siteJs = fs.readFileSync('js/site.js', 'utf8');
const siteCtx = { exports: {} };
vm.runInNewContext(siteJs.replace('const site', 'exports.site'), siteCtx);
const tagCN = siteCtx.exports.site?.tagCN || {};
const usedTags = new Set(posts.flatMap(p => p.tags));
usedTags.forEach(tag => {
  if (!tagCN[tag]) fail(`Tag "${tag}" used in posts but missing from site.tagCN`);
});

// ── Done ──
if (errors) {
  console.error(`\n${errors} error(s) found.`);
  process.exit(1);
} else {
  console.log('All checks passed.');
}
